add Debian 8 support

diff --git a/unix_env/kiwid b/unix_env/kiwid
--- a/unix_env/kiwid
+++ b/unix_env/kiwid
@@ -9,20 +9,42 @@
 # Description: run kiwi daemon
 ### END INIT INFO
 
+# set false when controlling SPI hardware directly (PIO mode):
+USE_SPIDEV=true
+
 KIWID=kiwid
 KIWID_EXEC=/usr/local/bin/$KIWID
 KIWID_ARGS="-bg"
 
+# Bug workaround: For Debian 8, BB-SPIDEV0 must be loaded via /boot/uEnv.txt
+# to config pmux properly. So set LOAD_SPI=no in that case.
+
+SLOTS="/sys/devices/platform/bone_capemgr/slots"	# Debian 8
+if test ! -f ${SLOTS} ; then
+	echo DEBIAN 7
+	LOAD_SPI=yes
+	SLOTS=`ls /sys/devices/bone_capemgr.*/slots`	# Debian 7
+else
+	echo DEBIAN 8
+	LOAD_SPI=no
+fi
+
 DEV=kiwi
-#DEV=test
 DEVID=cape-bone-${DEV}
 
-# select when controlling SPI hardware directly:
-#DEV_SPI=${DEV}-S
-#DEVID_SPI=cape-bone-${DEV_SPI}
-# select when using SPIDEV driver (with built-in DMA) for SPI:
-DEV_SPI=SPIDEV0
-DEVID_SPI=BB-${DEV_SPI}
+if ${USE_SPIDEV} ; then
+	# use SPIDEV driver (with built-in DMA) for SPI:
+	echo USE_SPIDEV
+	DEV_SPI=SPIDEV0
+	DEVID_SPI=BB-${DEV_SPI}
+else
+	echo USE_SPIPIO
+	DEV_SPI=${DEV}-S
+	DEVID_SPI=cape-bone-${DEV_SPI}
+	LOAD_SPI=yes
+fi
+
+echo LOAD_SPI = ${LOAD_SPI}
 
 DEV_PRU=${DEV}-P
 DEVID_PRU=cape-bone-${DEV_PRU}
@@ -30,7 +52,6 @@ DEVID_PRU=cape-bone-${DEV_PRU}
 CAPE=${DEVID}-00A0
 SPI=${DEVID_SPI}-00A0
 PRU=${DEVID_PRU}-00A0
-SLOTS=`ls /sys/devices/bone_capemgr.*/slots`
 
 [ -x $KIWID_EXEC ] || exit 1
 
@@ -46,47 +67,46 @@ case "$1" in
 # don't unload old slot because this is known to cause panics; must reboot
 	fi
 
-	if ! grep -q ${DEV} $SLOTS ; then
+	if ! grep -q ${DEVID} ${SLOTS} ; then
 		echo load ${DEV} device tree;
-		echo ${DEVID} > $SLOTS;
+		echo ${DEVID} > ${SLOTS};
 		sleep 2;
 	fi
 
 # SPI
-	if test \( ! -f /lib/firmware/${SPI}.dtbo \) -o \( /lib/firmware/${SPI}.dts -nt /lib/firmware/${SPI}.dtbo \) ; then
+	if test \( -f /lib/firmware/${SPI}.dts \) -a \( \( ! -f /lib/firmware/${SPI}.dtbo \) -o \( /lib/firmware/${SPI}.dts -nt /lib/firmware/${SPI}.dtbo \) \) ; then
 		echo compile ${DEV_SPI} device tree;
 		dtc -O dtb -o /lib/firmware/${SPI}.dtbo -b 0 -@ /lib/firmware/${SPI}.dts;
 # don't unload old slot because this is known to cause panics; must reboot
 	fi
 
-	if ! grep -q ${DEV_SPI} $SLOTS ; then
-		echo load ${DEV_SPI} device tree;
-		echo ${DEVID_SPI} > $SLOTS;
-		sleep 2;
+	if [ "x${LOAD_SPI}" = "xyes" ] ; then
+		if ! grep -q ${DEVID_SPI} ${SLOTS} ; then
+			echo load ${DEV_SPI} device tree;
+			echo ${DEVID_SPI} > ${SLOTS};
+			sleep 2;
+		fi
 	fi
 
 # PRU (future)
 	if test \( ! -f /lib/firmware/${PRU}.dtbo \) -o \( /lib/firmware/${PRU}.dts -nt /lib/firmware/${PRU}.dtbo \) ; then
 		echo compile ${DEV_PRU} device tree;
-		(cd /lib/firmware; dtc -O dtb -o ${PRU}.dtbo -b 0 -@ ${PRU}.dts);
+		dtc -O dtb -o /lib/firmware/${PRU}.dtbo -b 0 -@ /lib/firmware/${PRU}.dts;
 # don't unload old slot because this is known to cause panics; must reboot
 	fi
 	
-	if ! grep -q ${DEV_PRU} $SLOTS ; then
+	if ! grep -q ${DEVID_PRU} ${SLOTS} ; then
 		echo load ${DEV_PRU} device tree;
-		echo ${DEVID_PRU} > $SLOTS;
+		echo ${DEVID_PRU} > ${SLOTS};
 	fi
 
-# the test fixture is started separately by the Cloud9 IDE
-	if [ $DEV != "test" ] ; then
-		echo -n "Start kiwid: "
-		start-stop-daemon --start --background --exec $KIWID_EXEC -- $KIWID_ARGS
-		RETVAL=$?
-		if [ $RETVAL -eq 0 ] ; then
-			echo "OK"
-		else
-			echo "FAIL"
-		fi
+	echo -n "Start kiwid: "
+	start-stop-daemon --start --background --exec $KIWID_EXEC -- $KIWID_ARGS
+	RETVAL=$?
+	if [ $RETVAL -eq 0 ] ; then
+		echo "OK"
+	else
+		echo "FAIL"
 	fi
 
     # have to do something here that returns zero status, otherwise systemd immediately stops us. Why?
@@ -94,15 +114,13 @@ case "$1" in
     ;;
 
   stop)
-	if [ $DEV != "test" ] ; then
-		echo -n "Stopping kiwid: "
-		start-stop-daemon --stop --name $KIWID
-		RETVAL=$?
-		if [ $RETVAL -eq 0 ] ; then
-			echo "OK"
-		else
-			echo "FAIL"
-		fi
+	echo -n "Stopping kiwid: "
+	start-stop-daemon --stop --name $KIWID
+	RETVAL=$?
+	if [ $RETVAL -eq 0 ] ; then
+		echo "OK"
+	else
+		echo "FAIL"
 	fi
     ;;
 
